---
title: Chart/圖表（DiagrammeR）
author: ''
date: '2019-06-12'
slug: chart
categories:
  - R
tags: []
---
## 儒学的做人准则：

>《礼记·大学》：“古之欲明明德于天下者，先治其国；欲治其国者，先齐其家；欲齐其家者，先修其身；欲修其身者，先正其心；欲正其心者，先诚其意；欲诚其意者，先致其知，致知在格物。物格而后知至，知至而后意诚，意诚而后心正，心正而后身修，身修而后家齐，家齐而后国治，国治而后天下平。”

```{r}
library(DiagrammeR)
DiagrammeR::grViz("
digraph RmarkDown {
graph [rankdir = LR]
node [shape=rectangle
  style=filled
  color=orange
  fillcolor=salmon
  fontcolor=white
  arrowcolor=red
  alpha=55
  fontname = '微软雅黑']
edge [color = grey]
'修身' -> '齐家'
'齐家' -> '治国'
'治国' -> '平天下'
    }
    ", width=600)
```

## 权力的游戏最终季：是人性的扭曲还是道德的沦丧？
>盼星星盼月亮终于盼来了权游（GOT）的完结季，然而威风了八季的夜王被一刀毙命，开创了反派死于话少的先河；和蔼可亲的丹妮莉丝一言不合直接屠城，莫名走上了父亲的老路；布兰白捡一个铁王座，或成最终赢家……佳作逃不过烂尾的宿命，只好默默吐槽猪油蒙了心的编剧(:з」∠)

```{r}
library(DiagrammeR)
DiagrammeR("
sequenceDiagram;
马丁->>编剧:进度还来得及吗;
编剧->>马丁:恐怕有点悬;
马丁->>编剧:那我先把结局告诉你们吧;
马丁->>编剧:这个结局两位大爷满意吗;
alt 如果满意
编剧->>马丁: 很满意;
马丁->>编剧:递过书稿;
编剧->>马丁:还你一个歪到八姨妈家的结局;
马丁->>观众读者:递过书稿;
else 不满意
编剧->>马丁:你怎么能妨碍我们恰烂钱;
观众读者->>马丁:这才是我们想要的结局啊;
end
           ")

```

